/* 系统配置表 */
CREATE TABLE IF NOT EXISTS CONFIG
(
    CODE   VARCHAR(64) NOT NULL,
    DATA   VARCHAR(255),
    REMARK VARCHAR(512),
    TYPE   VARCHAR(64),
    PRIMARY KEY (CODE)
);

/* 首页链接表 */
CREATE TABLE IF NOT EXISTS LINK
(
    ID     BIGINT       NOT NULL,
    OPEN   VARCHAR(16),
    REMARK VARCHAR(512),
    SORT   INTEGER,
    TITLE  VARCHAR(255) NOT NULL,
    TYPE   VARCHAR(64),
    URL    VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

/* 网址收藏表 */
CREATE TABLE IF NOT EXISTS MARK
(
    ID     BIGINT       NOT NULL,
    REMARK VARCHAR(1024),
    SOURCE VARCHAR(16),
    TITLE  VARCHAR(255) NOT NULL,
    URL    VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

/* 网址收藏和标签关系表 */
CREATE TABLE IF NOT EXISTS MARK_TAG
(
    MARK_ID BIGINT NOT NULL,
    TAG_ID  BIGINT NOT NULL,
    PRIMARY KEY (MARK_ID, TAG_ID)
);

/* 收藏标签表 */
CREATE TABLE IF NOT EXISTS TAG
(
    ID   BIGINT       NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);